version: '3.8'

services:
  # ... existing code ...

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./alert-system/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - echo-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./alert-system/grafana/provisioning:/etc/grafana/provisioning
      - ./alert-system/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - echo-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  echo-network:
    driver: bridge 