version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: 
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - auth-service
      - chatbot-service
      - nlp-engine
      - dashboard-service

  # Service d'authentification
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/echo_auth
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
    depends_on:
      - db

  # Service de chatbot
  chatbot-service:
    build:
      context: ../chatbot-service
      dockerfile: Dockerfile
    environment:
      - NLP_SERVICE_URL=http://nlp-engine:5000
      - ALERT_SERVICE_URL=http://alert-system:5001
    depends_on:
      - nlp-engine
      - alert-system

  # Moteur NLP
  nlp-engine:
    build:
      context: ../nlp-engine
      dockerfile: Dockerfile
    environment:
      - MODEL_PATH=/app/models
      - REDIS_URL=redis://redis:6379
    volumes:
      - nlp_models:/app/models
    depends_on:
      - redis

  # Service de tableau de bord
  dashboard-service:
    build:
      context: ../dashboard-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api-gateway:8000
      - MONGODB_URI=mongodb://mongodb:27017/echo_dashboard
    depends_on:
      - mongodb
      - api-gateway

  # Collecteur de données
  data-collector:
    build:
      context: ../data-collector
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/echo_data
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  # Système d'alerte
  alert-system:
    build:
      context: ../alert-system
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - ALERT_THRESHOLD=0.8
    depends_on:
      - redis

  # Base de données PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=echo_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # MongoDB
  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  # Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  nlp_models:
